#!/bin/bash

here=$(pwd)
prereq=1



# if RPi
# need spi_serial, PIL, Adafruit_GPIO, Adafruit SSD1306

echo "**CHECKING HAT EEPROM"
echo "You should see 'Enhanced Radio Devices' on the next line."
cat /proc/device-tree/hat/vendor
echo
echo "You should see the name of the hat on the next line."
cat /proc/device-tree/hat/product
echo

# in this part install cmake TODO make of of those @if things
apt-get install build-essential
#maybe I can just do #####sudo apt-get install cmake
wget http://www.cmake.org/files/v3.14/cmake-3.14.1.tar.gz
tar xf cmake-3.14.1.tar.gz
cd cmake-3.14.1
./configure
make
./bootstrap
make
make install
cd $here

### install json-c

if ! $(python -c "import mraa"); then  #note "import sys; sys.path.append('/home/pi/ExplorerTest/libs/mraa') doesn't work
sudo apt-get install build-essential swig3.0 python-dev nodejs-dev cmake libjson-c-dev
git clone https://github.com/intel-iot-devkit/mraa.git libs/mraa
cd libs/mraa
mkdir build
cd build
cmake ..
make
make install
cd $here
fi

# get spi_serial and install
if ! $(python -c "import spi_serial"); then
echo "**INSTALLING SPI_SERIAL"
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi

git clone https://github.com/EnhancedRadioDevices/spi_serial.git libs/spi_serial
cd libs/spi_serial
python setup.py install
cd $here
fi
reset_spi_serial.py


# get Adafruit_GPIO
if ! $(python -c "import Adafruit_GPIO"); then
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi
echo "**INSTALLING ADAFRUIT_GPIO"
git clone https://github.com/adafruit/Adafruit_Python_GPIO.git libs/Adafruit_Python_GPIO 
cd libs/Adafruit_Python_GPIO
python setup.py install
cd $here
fi


# get Adafruit_SSD1306
if ! $(python -c "import Adafruit_SSD1306"); then
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi
echo "**INSTALLING RPi.GPIO"
pip install RPi.GPIO
git clone https://github.com/adafruit/Adafruit_Python_SSD1306.git libs/Adafruit_Python_SSD1306
cd libs/Adafruit_Python_SSD1306
python setup.py install
cd $here


# get PIL and install
echo "**INSTALLING PIL"
pip install pillow

fi

# run shapes
echo "**RUNNING shapes.py"
echo "You should see some shapes and a hello world message on your screen."
python shapes.py
#if Edison


#end if

# run cc1110 test
echo "**RUNNING cc1110_set_leds.py"
echo "You should see the two Explorer LEDs blink, then stay on."
python cc1110_set_leds.py
