#!/bin/bash

here=$(pwd)
prereq=1



# if RPi
# need spi_serial, PIL, Adafruit_GPIO, Adafruit SSD1306

echo "**CHECKING HAT EEPROM"
echo "You should see 'Enhanced Radio Devices' on the next line."
cat /proc/device-tree/hat/vendor
echo
echo "You should see the name of the hat on the next line."
cat /proc/device-tree/hat/product
echo

# get mraa and install
if ! $(python -c "import mraa"); then
sudo apt-get install libpcre3-dev cmake python-dev swig
git clone https://github.com/intel-iot-devkit/mraa.git
mkdir mraa/buld && cd$_
cmake .. -DBUILDSWIGNODE=OFF
make
make install
cd $here
fi

# get spi_serial and install
if ! $(python -c "import spi_serial"); then
echo "**INSTALLING SPI_SERIAL"
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi
git clone https://github.com/EnhancedRadioDevices/spi_serial.git libs/spi_serial
cd libs/spi_serial
python setup.py install
cd $here
fi


# get Adafruit_GPIO
if ! $(python -c "import Adafruit_GPIO"); then
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi
echo "**INSTALLING ADAFRUIT_GPIO"
git clone https://github.com/adafruit/Adafruit_Python_GPIO.git libs/Adafruit_Python_GPIO 
cd libs/Adafruit_Python_GPIO
python setup.py install
cd $here
fi

# get Adafruit_SSD1306
if ! $(python -c "import Adafruit_SSD1306"); then
if [[ $prereq ]]; then
apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git
prereq=0
fi
echo "**INSTALLING RPi.GPIO"
pip install RPi.GPIO
git clone https://github.com/adafruit/Adafruit_Python_SSD1306.git libs/Adafruit_Python_SSD1306
cd libs/Adafruit_Python_SSD1306
python setup.py install
cd $here

# get PIL and install
echo "**INSTALLING PIL"
pip install pillow

fi

echo "if spi* is NOT in the result of 'ls /dev',"
echo "then add the following line to /boot/config.txt: dtparam=spi=on and reboot the pi. Then run the installation file again"
reset_spi_serial.py

# run shapes
echo "**RUNNING shapes.py"
echo "You should see some shapes and a hello world message on your screen."
echo "If you get an IOError, then run sudo raspi-config and on the next screen choose:"
echo "1. Interfacing Options"
echo "2. I2C"
python shapes.py
#if Edison


#end if

# run cc1110 test
echo "**RUNNING cc1110_set_leds.py"
echo "You should see the two Explorer LEDs blink, then stay on."
python cc1110_set_leds.py
